name: Tag and Release Action
description: This action tags the release and optionally updates the major version branch.

inputs:
  version:
    description: 'The version to be used for the tag'
    required: true
  major:
    description: 'The major version to be used for the branch'
    required: false

runs:
  using: 'composite'
  steps:
  - name: Tag release and update major branch
    run: |
      git config user.name "github-actions"
      git config user.email "github-actions@github.com"
      git tag ${{ inputs.version }}
      git push origin ${{ inputs.version }}

      # Get current version
      latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
      IFS='.' read -r major minor patch <<<"${latest_tag#v}"

      # Update or create major version branch if major input greater than current
      if [ "${{ inputs.major }}" > ${major} ]; then    
        git fetch origin
        git branch -f ${{ inputs.major }}
        git push origin ${{ inputs.major }} --force
      fi
    shell: bash
