name: Tag and Release Action
description: This action tags the release and optionally updates the major version branch.

inputs:
  version:
    description: 'The version to be used for the tag'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Tag release and update major branch
    env:
      VERSION: ${{ inputs.version }}
    run: |
      git config user.name "github-actions"
      git config user.email "github-actions@github.com"
      git tag -f $VERSION
      git push origin $VERSION --force

      # Only proceed if on main branch
      current_branch=$(git rev-parse --abbrev-ref HEAD)
      if [ "$current_branch" = "main" ]; then
        IFS='.' read -r major minor patch <<<"${VERSION#v}"
        git fetch origin
        git branch -f "v${major}"
        git push origin "v${major}" --force
      fi
    shell: bash
