name: Tag and Release Action
description: This action tags the release and optionally updates the major version branch.

inputs:
  version:
    description: 'The version to be used for the tag'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Tag release and update major branch
    env:
      VERSION: ${{ inputs.version }}
    run: |
      git config user.name "github-actions"
      git config user.email "github-actions@github.com"
      git tag -f ${{ inputs.version }}
      git push origin ${{ inputs.version }} --force

      # Get current version
      latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.1")
      IFS='.' read -r major minor patch <<<"${latest_tag#v}"
      IFS='.' read -r vmajor vminor vpatch <<<"${VERSION#v}"

      # Update or create major version branch if major input greater than current
      if [ ${vmajor} > ${major} ]; then    
        git fetch origin
        git branch -f "v${vmajor}"
        git push origin "v${vmajor}" --force
      fi
    shell: bash
