name: Dockerhub Release Action
description: This action builds a Docker image, and pushes the image to DockerHub.

inputs:
  dockerhub_username:
    description: 'Your DockerHub username'
    required: true
  dockerhub_token:
    description: 'Your DockerHub access token'
    required: true
  publish_snapshot:
    description: 'Whether to publish snapshot versions (default: "false")'
    required: false
    default: 'false'
  snapshot_suffix:
    description: 'The suffix to use for snapshot versions (default: "snapshot")'
    required: false
    default: 'snapshot'

runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Log in to DockerHub
    uses: docker/login-action@v3
    if: ${{ inputs.publish_snapshot == 'true' || github.ref == 'refs/heads/main' }}
    with:
      username: ${{ inputs.dockerhub_username }}
      password: ${{ inputs.dockerhub_token}}

  - name: Set version variables
    id: vars
    if: ${{ inputs.publish_snapshot == 'true' || github.ref == 'refs/heads/main' }}
    uses: ./.github/actions/update-version-action
    with:
      snapshot_suffix: ${{ inputs.snapshot_suffix || 'snapshot' }}

  - name: Build Docker image
    run: |
      docker buildx build \
        --cache-from=type=local,src=/tmp/.buildx-cache \
        --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
        -t ${{ inputs.dockerhub_username }}/devops-toolkit:${{ steps.vars.outputs.version }} .
    shell: bash

  - name: Push Docker image
    if: ${{ inputs.publish_snapshot == 'true' || github.ref == 'refs/heads/main' }}
    run: |
      docker push ${{ inputs.dockerhub_username }}/devops-toolkit:${{ steps.vars.outputs.version }}
    shell: bash

  - name: Tag release and update major branch
    uses: ./.github/actions/tag-and-release-action
    if: ${{ steps.vars.outputs.is_release == 'true' }}
    with:
      version: ${{ steps.vars.outputs.version }}
      major: ${{ steps.vars.outputs.major }}
