# This action updates the version of the repository based on the branch name and latest tag.
# To update major version branch, you must run the following commands, for example from v2 to v3:
# git tag 3.0.0
# git push origin 3.0.0
# To update minor version branch, you must run the following commands, for example from v2.0 to v2.1:
# git tag 2.1.0
# git push origin 2.1.0
# To update patch version branch, nothing else is required.
name: Update repo version
description: Updates the version of the repo based on the branch name and latest tag.

inputs:
  snapshot_suffix:
    description: 'Suffix for snapshot versions'
    required: false
    default: 'snapshot'
outputs:
  version:
    description: 'The version to be used for the Docker image'
    value: ${{ steps.vars.outputs.version }}
  major:
    description: 'The major version to be used for the Docker image'
    value: ${{ steps.vars.outputs.major }}
runs:
  using: 'composite'
  steps:
  - name: Set version variables
    id: vars
    shell: bash
    env:
      SNAPSHOT_SUFFIX: ${{ inputs.snapshot_suffix  || 'SNAPSHOT' }}
    run: |
      if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
        # Get latest tag, bump patch version
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.1")
        IFS='.' read -r major minor patch <<<"${latest_tag#v}"
        patch=$((patch+1))
        new_version="v${major}.${minor}.${patch}"
        echo "version=$new_version" >> $GITHUB_OUTPUT
        echo "major=${major}" >> $GITHUB_OUTPUT
        echo "# --- Release version --- #"
        echo "Latest tag: $latest_tag"
        echo "New version: $new_version"
        echo "Major version: v${major}"
      else
        # For feature branches, use snapshot version
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.1")
        IFS='.' read -r major minor patch <<<"${latest_tag#v}"
        current_version="v${major}.${minor}.${patch}"
        snap_version="${current_version}-${SNAPSHOT_SUFFIX}"
        echo "version=${snap_version}" >> $GITHUB_OUTPUT
        echo "major=${major}" >> $GITHUB_OUTPUT
        echo "# --- Snapshot version --- #"
        echo "Snapshot version: ${version}-$SNAPSHOT_SUFFIX"
      fi
