name: Release workflow for DevOps Toolkit
on:
  push:
    branches:
      - main
      - 'feature/*'
    paths-ignore:
      - '**.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version variables
        id: vars
        uses: ./.github/actions/update-version-action
        with:
          snapshot_suffix: ${{ vars.SNAPSHOT_SUFFIX || 'snapshot' }}
        
      - name: Tag release and update major branch
        uses: ./.github/actions/tag-and-release-action
        with:
          version: ${{ steps.vars.outputs.version }}
